/**
 * Created by ruanhaojian on 16/8/22.
 */

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'

export const TOGGLE_NAV_MENU = 'TOGGLE_NAV_MENU'
export const OPEN_NAV_MENU = 'OPEN_NAV_MENU'
export const CLOSE_NAV_MENU = 'CLOSE_NAV_MENU'
export const FULL_NAV_MENU = 'FULL_NAV_MENU'

export const TRIGGER_LOAD_ANIMATION = 'TRIGGER_LOAD_ANIMATION'
export const TRIGGER_LOAD_ANIMATION_DONE = 'TRIGGER_LOAD_ANIMATION_DONE'
export const TRIGGER_LOAD_ANIMATION_HIDE = 'TRIGGER_LOAD_ANIMATION_HIDE'
export const TRIGGER_LOAD_ANIMATION_FAILED = 'TRIGGER_LOAD_ANIMATION_FAILED'
export const TRIGGER_LOAD_ANIMATION_RESET = 'TRIGGER_LOAD_ANIMATION_RESET'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED'
export const USER_PROFILE_REPOS_RECEIVED = 'USER_PROFILE_REPOS_RECEIVED'