/**
 * Created by ruanhaojian on 16/8/22.
 */

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'

export const TOGGLE_NAV_MENU = 'TOGGLE_NAV_MENU'
export const OPEN_NAV_MENU = 'OPEN_NAV_MENU'
export const CLOSE_NAV_MENU = 'CLOSE_NAV_MENU'
export const FULL_NAV_MENU = 'FULL_NAV_MENU'

export const TRIGGER_LOAD_ANIMATION = 'TRIGGER_LOAD_ANIMATION'
export const TRIGGER_LOAD_ANIMATION_DONE = 'TRIGGER_LOAD_ANIMATION_DONE'
export const TRIGGER_LOAD_ANIMATION_HIDE = 'TRIGGER_LOAD_ANIMATION_HIDE'
export const TRIGGER_LOAD_ANIMATION_FAILED = 'TRIGGER_LOAD_ANIMATION_FAILED'
export const TRIGGER_LOAD_ANIMATION_RESET = 'TRIGGER_LOAD_ANIMATION_RESET'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED'
export const USER_PROFILE_REPOS_RECEIVED = 'USER_PROFILE_REPOS_RECEIVED'

export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_RECEIVED = 'USERS_RECEIVED'

export const USER_REPOS_RECEIVED = 'USER_REPOS_RECEIVED'
export const USER_REPOS_NEXT_PAGE_RECEIVED = 'USER_REPOS_NEXT_PAGE_RECEIVED'
export const USER_REPOS_COMPLETE = 'USER_REPOS_COMPLETE'


export const REPO_DETAIL_RECEIVED_ALL = 'REPO_DETAIL_RECEIVED_ALL'
